import { Agent, AgentManifest, AgentInput, AgentOutput, AgentContext, AgentEvent } from '../types.js';

export class FounderCoSAgent implements Agent {
  constructor(public manifest: AgentManifest) {}

  async initialize(): Promise<void> {
    console.log(`[${this.manifest.agent_id}] Initialized`);
  }

  async run(input: AgentInput, context: AgentContext): Promise<AgentOutput> {
    context.log('Running Founder CoS Agent', { trigger: input.trigger });

    const prompt = this.buildPrompt(input);

    const llmResponse = await context.llm({
      messages: [
        { role: 'system', content: this.manifest.purpose },
        { role: 'user', content: prompt },
      ],
      task_type: 'summary',
    });

    const content = llmResponse.content;

    await context.memory.save({
      memory_type: 'output',
      content: content,
      importance: 0.85,
    });

    return {
      summary: 'Daily briefing generated',
      content,
      decisions: [
        {
          decision_id: `dec_${Date.now()}`,
          title: 'Review priority list from briefing',
          rationale: 'Generated by Founder CoS Agent',
          requires_approval: false,
        },
      ],
    };
  }

  async wake(event: AgentEvent): Promise<AgentInput | null> {
    if (this.manifest.sleep_cycle.emergency_topics.includes(event.topic)) {
      return {
        trigger: 'wake',
        request: `Handle emergency event: ${event.event_type}`,
        event,
      };
    }
    return null;
  }

  async sleep(): Promise<void> {
    console.log(`[${this.manifest.agent_id}] Sleeping`);
  }

  async shutdown(): Promise<void> {
    console.log(`[${this.manifest.agent_id}] Shutdown`);
  }

  private buildPrompt(input: AgentInput): string {
    if (input.request) return input.request;
    if (input.trigger === 'scheduled') {
      return 'Generate the daily founder briefing. Include priorities, decisions needed, agent status, and risks.';
    }
    return 'Process the incoming event and produce a concise summary for the founder.';
  }
}
