import { Agent, AgentManifest, AgentInput, AgentOutput, AgentContext, AgentEvent } from '../types.js';

export class ProductManagerAgent implements Agent {
  constructor(public manifest: AgentManifest) {}

  async initialize(): Promise<void> {
    console.log(`[${this.manifest.agent_id}] Initialized`);
  }

  async run(input: AgentInput, context: AgentContext): Promise<AgentOutput> {
    context.log('Running Product Manager Agent', { trigger: input.trigger });

    const request = input.request ?? 'Create a PRD for the most important customer-asked feature.';

    const llmResponse = await context.llm({
      messages: [
        { role: 'system', content: this.manifest.purpose },
        { role: 'user', content: this.buildPrompt(request) },
      ],
      task_type: 'creative',
    });

    const prdContent = llmResponse.content;

    // Extract title from first line
    const title = prdContent.split('\n')[0].replace(/^#+\s*/, '').slice(0, 80) || 'New Feature';
    const workflowId = input.workflow_id;

    // Create issue in tracker
    const issueResult = await context.tools.request('github.create_issue', {
      title: `[PRD] ${title}`,
      body: prdContent,
      labels: ['prd', 'product'],
    });

    await context.memory.save({
      memory_type: 'output',
      content: prdContent,
      importance: 0.85,
      source_event_id: input.event?.event_id,
    });

    return {
      summary: `PRD created: ${title}`,
      content: prdContent,
      decisions: [
        {
          decision_id: `prd_${Date.now()}`,
          title: `Prioritize ${title}`,
          rationale: 'Generated by Product Manager Agent based on input',
          requires_approval: false,
        },
      ],
      events: [
        {
          event_id: `evt_${Date.now()}`,
          event_type: 'product.prd',
          topic: 'product.prd',
          source_agent_id: this.manifest.agent_id,
          org_id: context.org_id,
          correlation_id: context.run_id,
          timestamp: new Date().toISOString(),
          payload: {
            title,
            content: prdContent,
            issue_number: issueResult.issue_number,
            workflow_id: workflowId,
          },
        },
      ],
    };
  }

  async wake(event: AgentEvent): Promise<AgentInput | null> {
    if (this.manifest.subscribed_topics.includes(event.topic)) {
      return {
        trigger: 'event',
        event,
        request: 'Update backlog or PRD based on new customer intelligence or research.',
      };
    }
    return null;
  }

  async sleep(): Promise<void> {
    console.log(`[${this.manifest.agent_id}] Sleeping`);
  }

  async shutdown(): Promise<void> {
    console.log(`[${this.manifest.agent_id}] Shutdown`);
  }

  private buildPrompt(request: string): string {
    return `Create a concise product requirements document (PRD) for the following request.
Include: Problem, Goal, User Stories, Acceptance Criteria, Open Questions.

Request: ${request}`;
  }
}
